# Licensed to Julian Hyde under one or more contributor license
# agreements.  See the NOTICE file distributed with this work
# for additional information regarding copyright ownership.
# Julian Hyde licenses this file to you under the Apache
# License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License.  You may obtain a
# copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.  See the License for the specific
# language governing permissions and limitations under the
# License.
#
name: Java CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch: # allow manual triggering
  schedule:
    # Run at 0543 UTC on the 7th day of each month
    #        m  h  dom mon dow
    - cron: '43 05   7   *   *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        java-version: [ "11" ]
        guava-version: [ "33.4.5-jre" ]
        hsqldb-version: [ "" ]
        checkstyle-version: [ "" ]
        javadoc: [ false ]
        include:
          - java-version: "8"
            guava-version: "23.1"
            hsqldb-version: "2.5.1"
            checkstyle-version: "9.3"
          - java-version: "11"
          - java-version: "17"
            javadoc: true
          - java-version: "21"
            guava-version: "31.1-jre"
          - java-version: "21"

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          GOALS=verify
          if [ "${{ matrix.javadoc }}" = true ]
          then
            GOALS="$GOALS javadoc:javadoc javadoc:test-javadoc"
          fi
          DEFS="-Dmorel.ci"
          if [ "${{ matrix.checkstyle-version }}" ]
          then
            DEFS="$DEFS -Dcheckstyle.version=${{ matrix.checkstyle-version }}"
          fi
          if [ "${{ matrix.guava-version }}" ]
          then
            DEFS="$DEFS -Dguava.version=${{ matrix.guava-version }}"
          fi
          if [ "${{ matrix.hsqldb-version }}" ]
          then
            DEFS="$DEFS -Dhsqldb.version=${{ matrix.hsqldb-version }}"
          fi
          mvn $DEFS --batch-mode --update-snapshots $GOALS

# End main.yml
